version: '3'
services:
  todoist-inbox-organizer:
    build: .
    volumes:
      - .:/app
    ports:
      - "8008:8008"
    environment:
      - TODOIST_API_KEY=${TODOIST_API_KEY}
      - DEBUG=${DEBUG}
    restart: always
